apiVersion: apps/v1
kind: Deployment
metadata:
  name: airis-deployment
  namespace: airis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airis
  template:
    metadata:
      labels:
        app: airis
    spec:
      containers:
      - name: airis
        image: ghcr.io/airis/airis:main
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service.airis.svc.cluster.local:11434"
        tty: true
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: airis-pvc          