apiVersion: v1
kind: Service
metadata:
  name: airis-service
  namespace: airis
spec:
  type: NodePort  # Use LoadBalancer if you're on a cloud that supports it
  selector:
    app: airis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # If using NodePort, you can optionally specify the nodePort:
      # nodePort: 30000